const fs = require('fs');

const htmlFile = 'index.html';
let html = fs.readFileSync(htmlFile, 'utf8');

const replacements = [
    // Page: Local Files
    ['<h3>Local Files</h3>', '<h3>Archivos Locales</h3>'],
    ['Change Folder', 'Cambiar Carpeta'],

    // Page: Recent
    ['Recently played', 'Reproducido recientemente'],
    ['title="Clear History"', 'title="Borrar Historial"'],
    ['<span>Clear</span>', '<span>Borrar</span>'],

    // Page: Tracker Artist
    ['Unreleased Artist', 'Artista sin lanzamientos'],
    ['<span>Shuffle Play</span>', '<span>Reproducción aleatoria</span>'],
    ['title="Shuffle Play"', 'title="Reproducción aleatoria"'],
    ['title="Download"', 'title="Descargar"'],
    ['<span>Download All</span>', '<span>Descargar Todo</span>'],

    // Page: Album
    ['title="Play Album"', 'title="Reproducir Álbum"'],
    ['<span>Play Album</span>', '<span>Reproducir Álbum</span>'],
    ['title="Shuffle"', 'title="Aleatorio"'],
    ['<span>Shuffle</span>', '<span>Aleatorio</span>'],
    ['title="Mix"', 'title="Mix"'],
    ['<span>Mix</span>', '<span>Mix</span>'],
    ['title="Add to Playlist"', 'title="Añadir a Playlist"'],
    ['<span>Add to Playlist</span>', '<span>Añadir a Playlist"</span>'],
    ['from Artist', 'del Artista'],
    ['Similar Artists', 'Artistas Similares'],

    // Page: Playlist
    ['Suggested Songs From Your Playlist', 'Canciones sugeridas para tu playlist'],
    ['title="Refresh Recommendations"', 'title="Actualizar recomendaciones"'],

    // Page: Folder
    ['Delete Folder', 'Eliminar Carpeta'],

    // Page: Artist
    ['title="Artist Radio"', 'title="Radio del Artista"'],
    ['<span>Radio</span>', '<span>Radio</span>'],
    ['Popular Tracks', 'Pistas Populares'],
    ['Load Unreleased Projects', 'Cargar proyectos sin lanzamientos'],
    ['Unreleased Music', 'Música sin lanzamientos'],

    // Page: Track
    ['<div class="type">Song</div>', '<div class="type">Canción</div>'],
    ['More from Album', 'Más del Álbum'],
    ['Similar Tracks', 'Pistas Similares'],

    // Page: Profile
    ['Favorite Álbumes of All Time', 'Álbumes favoritos de todos los tiempos'],
    ['Recent Scrobbling', 'Scrobbling reciente'],
    ['Powered by Last.fm', 'Desarrollado por Last.fm'],
    ['Top Artists', 'Artistas principales'],
    ['Top Álbumes', 'Álbumes principales'],
    ['Top Tracks', 'Pistas principales'],

    // Settings General
    ['Search settings...', 'Buscar ajustes...'],
    ['>Appearance<', '>Apariencia<'],
    ['>Interface<', '>Interfaz<'],
    ['>Scrobbling<', '>Scrobbling<'],
    ['>Audio<', '>Audio<'],
    ['>System<', '>Sistema<'],
    ['>Theme<', '>Tema<'],
    ['Choose your preferred color scheme', 'Elige tu combinación de colores preferida'],
    ['data-theme="system">System<', 'data-theme="system">Sistema<'],
    ['>Black<', '>Negro<'],
    ['>White<', '>Blanco<'],
    ['>Dark<', '>Oscuro<'],
    ['Applied Community Theme', 'Tema de la comunidad aplicado'],
    ['Unapply Theme', 'Desaplicar tema'],
    ['Custom Theme', 'Tema personalizado'],
    ['>Reset<', '>Restablecer<'],
    ['>Community Themes<', '>Temas de la comunidad<'],
    ['Browse and apply themes created by the community', 'Explora y aplica temas creados por la comunidad'],
    ['Open Tienda de Temas', 'Abrir Tienda de Temas'],
    ['>Font<', '>Fuente<'],
    ['Choose from presets, Google Fonts, URLs, or upload your own', 'Elige entre preajustes, Google Fonts, URLs o sube la tuya propia'],
    ['>Preset<', '>Preajuste<'],
    ['>Apply<', '>Aplicar<'],
    ['Font Size', 'Tamaño de fuente'],
    ['Adjust the base font size (50% - 200%)', 'Ajustar el tamaño de fuente base (50% - 200%)'],
    ['Reset to default', 'Restablecer al valor predeterminado'],
    ['Waveform Seekbar', 'Barra de progreso de forma de onda'],
    ['Show a visual waveform of the track in the progress bar', 'Muestra una forma de onda visual de la pista en la barra de progreso'],
    ['(Experimental)', '(Experimental)'],
    ['Smooth Scrolling', 'Desplazamiento suave'],
    ['Provides a smoother scrolling experience with Lenis', 'Proporciona una experiencia de desplazamiento más suave con Lenis'],
    ['Album Cover Background', 'Fondo de portada del álbum'],
    ['Use the album cover as a blurred background on album pages and as primary color', 'Usa la portada del álbum como fondo borroso en las páginas del álbum y como color principal'],
    ['Dynamic Colors', 'Colores dinámicos'],
    ['Automatically change the app accent color based on the currently playing track\'s album art', 'Cambia automáticamente el color de acento de la app en función de la portada de la pista en reproducción'],
    ['Full-screen Visualizer', 'Visualizador en pantalla completa'],
    ['Enable particle visualizer in full-screen mode', 'Habilitar visualizador de partículas en modo de pantalla completa'],
    ['Visualizer Style', 'Estilo de visualizador'],
    ['Select the visualization style', 'Seleccionar el estilo de visualización'],
    ['Visualizer Mode', 'Modo de visualizador'],
    ['Choose how the visualizer is displayed in full-screen', 'Elige cómo se muestra el visualizador en pantalla completa'],
    ['Solid Background', 'Fondo Sólido'],
    ['Blended on Cover Art', 'Mezclado en la portada'],
    ['Smart Intensity Switching', 'Cambio Inteligente de Intensidad'],
    ['Automatically adjust visualizer intensity based on song energy', 'Ajustar automáticamente la intensidad del visualizador según la energía de la canción'],
    ['Visualizer Sensitivity', 'Sensibilidad del visualizador'],
    ['Adjust the intensity of the visualizer effects.', 'Ajustar la intensidad de los efectos del visualizador.'],
    ['Warning: High sensitivity may cause flashing lights and rapid motion, which can trigger seizures in people with photosensitive epilepsy.', 'Advertencia: La alta sensibilidad puede causar luces intermitentes y movimientos rápidos, que podrían desencadenar convulsiones en personas con epilepsia fotosensible.'],

    ['>Cycle Presets<', '>Ciclo de preajustes<'],
    ['Automatically change visualizer presets', 'Cambiar automáticamente los preajustes del visualizador'],
    ['Current Preset', 'Preajuste actual'],
    ['Cycle Duration', 'Duración del ciclo'],
    ['Seconds between preset changes', 'Segundos entre cambios de preajuste'],
    ['Randomize Presets', 'Preajustes Aleatorios'],
    ['Select next preset randomly instead of sequentially', 'Seleccionar el próximo preajuste al azar en lugar de en orden'],

    ['Show Recommended Songs', 'Mostrar canciones recomendadas'],
    ['Display recommended songs on the home page', 'Mostrar canciones recomendadas en la página de inicio'],
    ['Show Recommended Álbumes', 'Mostrar álbumes recomendados'],
    ['Display recommended albums on the home page', 'Mostrar álbumes recomendados en la página de inicio'],
    ['Show Recommended Artists', 'Mostrar artistas recomendados'],
    ['Display recommended artists on the home page', 'Mostrar artistas recomendados en la página de inicio'],
    ['Show Jump Back In', 'Mostrar "Vuelve a escuchar"'],
    ['Display recent albums, playlists, and mixes on the home page', 'Mostrar álbumes, playlists y mixes recientes en la página de inicio'],
    ['Show Editor\'s Picks', 'Mostrar "Selección del Editor"'],
    ['Display curated album selections on the home page', 'Mostrar selecciones de álbumes curadas en la página de inicio'],
    ['Shuffle Editor\'s Picks', 'Orden aleatorio de "Selección del Editor"'],
    ['Randomize the order of editor\'s picks on each load', 'Aleatorizar el orden de la selección del editor en cada carga'],

    ['Show Home in Sidebar', 'Mostrar "Inicio" en la barra lateral'],
    ['Display the Home link in the sidebar navigation', 'Mostrar el enlace de Inicio en la navegación de la barra lateral'],
    ['Show Library in Sidebar', 'Mostrar "Biblioteca" en la barra lateral'],
    ['Display the Library link in the sidebar navigation', 'Mostrar el enlace de Biblioteca en la navegación de la barra lateral'],
    ['Show Recent in Sidebar', 'Mostrar "Recientes" en la barra lateral'],
    ['Display the Recent link in the sidebar navigation', 'Mostrar el enlace de Recientes en la navegación de la barra lateral'],
    ['Show Unreleased in Sidebar', 'Mostrar "No lanzados" en la barra lateral'],
    ['Display the Unreleased link in the sidebar navigation', 'Mostrar el enlace de No lanzados en la navegación de la barra lateral'],
    ['Show Donate in Sidebar', 'Mostrar "Donar" en la barra lateral'],
    ['Display the Donate link in the sidebar navigation', 'Mostrar el enlace de Donar en la navegación de la barra lateral'],
    ['Show Settings in Sidebar', 'Mostrar "Ajustes" en la barra lateral'],
    ['Display the Settings link in the sidebar navigation', 'Mostrar el enlace de Ajustes en la navegación de la barra lateral'],
    ['Show About in Sidebar', 'Mostrar "Acerca de" en la barra lateral'],
    ['Display the About link in the sidebar navigation', 'Mostrar el enlace de Acerca de en la navegación de la barra lateral'],
    ['Show Download in Sidebar', 'Mostrar "Descargar" en la barra lateral'],
    ['Display the Download link in the sidebar navigation', 'Mostrar el enlace de Descargar en la navegación de la barra lateral'],
    ['Show Discord in Sidebar', 'Mostrar "Discord" en la barra lateral'],
    ['Display the Discord link in the sidebar navigation', 'Mostrar el enlace de Discord en la navegación de la barra lateral'],

    ['Close Modals on Navigation', 'Cerrar paneles al navegar'],
    ['Close open modals and panels (like lyrics, queue) when navigating back or to a new page', 'Cierra paneles abiertos (como letras, cola) al navegar hacia atrás o a una nueva página'],
    ['Intercept Back to Close Modals', 'Interceptar regreso para cerrar paneles'],
    ['When pressing back, close open modals/panels first without navigating. Press back again to actually go back.', 'Al presionar regresar, cierra primero los paneles abiertos sin navegar. Presiona regresar de nuevo para navegar realmente atrás.'],

    ['Scrobble Threshold', 'Umbral de Scrobble'],
    ['Percentage of track to play before scrobbling (1-100%)', 'Porcentaje de la pista a reproducir antes del scrobble (1-100%)'],
    ['Connect your Last.fm account to scrobble tracks', 'Conecta tu cuenta de Last.fm para registrar pistas'],
    ['Connect Last.fm', 'Conectar Last.fm'],
    ['Enter your Last.fm credentials:', 'Introduce tus credenciales de Last.fm:'],
    ['>Login<', '>Iniciar Sesión<'],
    ['Use OAuth Instead', 'Usar OAuth en su lugar'],
    ['Login with Username/Password', 'Iniciar sesión con Usuario/Contraseña'],
    ['Enable Scrobbling', 'Habilitar Scrobbling'],
    ['Automatically scrobble played tracks', 'Haz scrobble de las canciones reproducidas automáticamente'],
    ['Love on Like', 'Dar favorito al guardar'],
    ['Automatically \'love\' tracks on Last.fm when you like them', 'Haz que la pista tenga \'Me Gusta\' en Last.fm automáticamente al guardarla'],
    ['Use Custom API Credentials', 'Usar Credenciales de API Personalizadas'],
    ['Use your own Last.fm API key and secret', 'Usa tu propia API key y secret de Last.fm'],
    ['Custom API Credentials', 'Credenciales de API Personalizadas'],
    ['Save Credentials', 'Guardar Credenciales'],
    ['Connect your Libre.fm account to scrobble tracks', 'Conecta tu cuenta de Libre.fm para registrar pistas'],
    ['Connect Libre.fm', 'Conectar Libre.fm'],
    ['Automatically \'love\' tracks on Libre.fm when you like them', 'Haz que la pista tenga \'Me Gusta\' en Libre.fm automáticamente al guardarla'],

    ['Music Provider', 'Proveedor de música'],
    ['Default service for searching and streaming', 'Servicio predeterminado para búsquedas y streaming'],
    ['Streaming Quality', 'Calidad de streaming'],
    ['Quality for streaming playback', 'Calidad para la reproducción en streaming'],
    ['Download Quality', 'Calidad de descarga'],
    ['Quality for track downloads', 'Calidad para las descargas de pistas'],
    ['Lossless Container', 'Contenedor sin pérdida'],
    ['Container format for lossless downloads', 'Formato contenedor para descargas sin pérdida'],
    ['Cover Art Size', 'Tamaño de la portada'],
    ['Size for downloaded/embedded cover art', 'Tamaño para la portada descargada o incrustada'],
    ['Show Quality Badges', 'Mostrar insignias de calidad'],
    ['Display "HD" badge for Hi-Res tracks', 'Mostrar la insignia "HD" para las pistas de alta resolución'],
    ['Album release year', 'Año de lanzamiento del álbum'],
    ['Show original album year instead of track/remaster date', 'Mostrar el año original del álbum en lugar de la fecha de la pista/remasterización'],
    ['Gapless Playback', 'Reproducción sin pausas (Gapless)'],
    ['Play audio without interruption between tracks', 'Reproducir audio sin interrupciones entre pistas'],
    ['ReplayGain Mode', 'Modo ReplayGain'],
    ['Normalize volume across tracks', 'Normalizar el volumen en todas las pistas'],
    ['>Off<', '>Apagado<'],
    ['ReplayGain Pre-Amp', 'Pre-Amp ReplayGain'],
    ['Adjust gain manually (dB)', 'Ajustar ganancia manualmente (dB)'],
    ['Mono Audio', 'Audio Mono'],
    ['Combine left and right channels into mono', 'Combina los canales izquierdo y derecho en mono'],
    ['Exponential Volume', 'Volumen Exponencial'],
    ['Use logarithmic volume curve for finer low-volume control', 'Utiliza una curva de volumen logarítmica para un control más preciso a bajo volumen'],
    ['Playback Speed', 'Velocidad de reproducción'],
    ['Adjust playback speed (0.01x - 100x)', 'Ajustar la velocidad de reproducción (0.01x - 100x)'],
    ['>Equalizer<', '>Ecualizador<'],
    ['16-band parametric equalizer for fine audio control', 'Ecualizador paramétrico de 16 bandas para control de audio fino'],
    ['Built-in Presets', 'Preajustes Integrados'],
    ['>Flat<', '>Plano<'],
    ['Bass Boost', 'Refuerzo de graves'],
    ['Bass Reducer', 'Reductor de graves'],
    ['Treble Boost', 'Refuerzo de agudos'],
    ['Treble Reducer', 'Reductor de agudos'],
    ['Vocal Boost', 'Refuerzo vocal'],
    ['>Loudness<', '>Sonoridad<'],
    ['Classical', 'Clásica'],
    ['Electronic', 'Electrónica'],
    ['Acoustic', 'Acústica'],
    ['Podcast / Speech', 'Podcast / Habla'],
    ['Custom Presets', 'Preajustes Personalizados'],
    ['>Bands<', '>Bandas<'],
    ['Export EQ settings to text', 'Exportar ajustes EQ a texto'],
    ['Import EQ settings from text or file', 'Importar ajustes EQ desde texto o archivo'],
    ['Preset name (e.g., Home, Car, Work)', 'Nombre del preajuste (ej., Casa, Auto, Trabajo)'],
    ['Save current EQ as custom preset', 'Guardar EQ actual como preajuste personalizado'],
    ['Delete selected custom preset', 'Eliminar preajuste personalizado seleccionado'],
    ['Delete Preset', 'Eliminar Preajuste'],
    ['DB Range:', 'Rango DB:'],
    ['Freq Range:', 'Rango Frec:'],
    ['Preamp:', 'Preamp:'],

    ['Now Playing View Mode', 'Modo de Vista de Reproducción'],
    ['Choose what shows when you click the album art', 'Elige qué se muestra al hacer clic en la portada del álbum'],
    ['Go to Album', 'Ir al Álbum'],
    ['Fullscreen Mode', 'Modo Pantalla Completa'],
    ['Lyrics Panel', 'Panel de Letras'],
    ['Compact Artists', 'Artistas Compactos'],
    ['Show artist cards in a compact, horizontal layout', 'Mostrar tarjetas de artistas en un diseño horizontal compacto'],
    ['Compact Álbumes', 'Álbumes Compactos'],
    ['Show album cards in a compact, horizontal layout', 'Mostrar tarjetas de álbumes en un diseño horizontal compacto'],

    ['Zipped Bulk Downloads', 'Descargas masivas en ZIP'],
    ['Download multiple tracks as a single ZIP file (requires browser support)', 'Descargar múltiples pistas como un solo archivo ZIP (requiere soporte del navegador)'],
    ['Download Lyrics', 'Descargar Letras'],
    ['Include .lrc files when downloading tracks/albums', 'Incluir archivos .lrc al descargar pistas/álbumes'],
    ['Romaji Lyrics', 'Letras en Romaji'],
    ['Convert Japanese lyrics to Romaji (Latin characters)', 'Convierte letras japonesas a Romaji (caracteres latinos)'],
    ['Filename Template', 'Plantilla de nombre de archivo'],
    ['Customize download filenames. Available:', 'Personaliza los nombres de archivo de descarga. Disponibles:'],
    ['ZIP Folder Template', 'Plantilla de carpeta ZIP'],
    ['Customize album folder names. Available:', 'Personaliza los nombres de las carpetas de álbumes. Disponibles:'],
    ['Generate M3U', 'Generar M3U'],
    ['Generate M3U8', 'Generar M3U8'],
    ['Include M3U playlist files in downloads', 'Incluir archivos de playlist M3U en las descargas'],
    ['Include extended M3U8 playlist files in downloads', 'Incluir archivos de playlist M3U8 extendidos en las descargas'],
    ['Generate CUE', 'Generar CUE'],
    ['Include CUE sheets for gapless playback in downloads', 'Incluir hojas CUE para reproducción sin pausas en las descargas'],
    ['Generate NFO', 'Generar NFO'],
    ['Include NFO files for media center compatibility', 'Incluir archivos NFO para compatibilidad con media centers'],
    ['Generate JSON', 'Generar JSON'],
    ['Include JSON files with rich metadata', 'Incluir archivos JSON con metadatos enriquecidos'],
    ['Relative Paths', 'Rutas relativas'],
    ['Use relative paths in playlist files', 'Utilizar rutas relativas en archivos de playlist'],
    ['Separate Discs in ZIP', 'Discos separados en ZIP'],
    ['Put tracks in Disc folders when a release has multiple discs', 'Colocar pistas en carpetas de disco cuando un lanzamiento tiene múltiples discos'],

    ['>Cache<', '>Caché<'],
    ['Stores API responses to reduce requests', 'Almacena respuestas de API para reducir solicitudes'],
    ['Clear Cache', 'Borrar Caché'],
    ['Auto-Update App', 'Auto-Actualizar App'],
    ['Automatically reload when a new version is available', 'Recargar automáticamente cuando hay una nueva versión disponible'],
    ['>Analytics<', '>Estadísticas (Analytics)<'],
    ['Send anonymous usage data to help improve the app', 'Enviar datos de uso anónimos para ayudar a mejorar la app'],
    ['Reset Local Data', 'Restablecer Datos Locales'],
    ['Clear all local storage and cached data (does not affect cloud sync)', 'Borrar todo el almacenamiento local y los datos en caché (no afecta a la sincronización en la nube)'],
    ['Clear Cloud Data', 'Borrar Datos en la Nube'],
    ['Delete all your data from the cloud (cannot be undone)', 'Elimina todos tus datos de la nube (no se puede deshacer)'],
    ['Backup & Restore', 'Copia de Seguridad y Restauración'],
    ['Export or import your library and history as JSON', 'Exporta o importa tu biblioteca y tu historial en formato JSON'],
    ['>Export<', '>Exportar<'],
    ['>Import<', '>Importar<'],
    ['ADVANCED: Base de Datos/Autenticación Personalizada', 'AVANZADO: Base de Datos/Autenticación Personalizada'],
    ['Configure custom PocketBase and Firebase instances', 'Configura instancias personalizadas de PocketBase y Firebase'],
    ['>Configure<', '>Configurar<'],
    ['API Instances', 'Instancias API'],
    ['Manage and prioritize API instances.', 'Gestiona y prioriza instancias API.'],
    ['Refresh Instance List', 'Actualizar lista de instancias'],

    ['Blocked Content', 'Contenido bloqueado'],
    ['Manage artists, albums, and tracks you\'ve blocked from recommendations', 'Gestiona artistas, álbumes y pistas que has blocked de tus recomendaciones'],
    ['>Manage<', '>Gestionar<'],
    ['Clear All', 'Borrar Todo'],
    ['Blocked Artists', 'Artistas bloqueados'],
    ['Blocked Álbumes', 'Álbumes bloqueados'],
    ['Blocked Tracks', 'Pistas bloqueadas'],
    ['No blocked content', 'No hay contenido bloqueado'],

    ['About Monochrome', 'Acerca de Monochrome'],
    ['Monochrome is a lightweight, privacy-focused music streaming client designed for', 'Monochrome es un cliente de transmisión de música ligero y enfocado en la privacidad diseñado para'],
    ['high-fidelity audio playback. Built with modern web technologies, it provides a clean,', 'reproducción de audio de alta fidelidad. Creado con tecnologías web modernas, proporciona una experiencia'],
    ['distraction-free listening experience.', 'de escucha limpia y sin distracciones.'],
    ['>Features<', '>Características<'],
    ['High-quality lossless audio streaming', 'Streaming de audio sin pérdida de alta calidad'],
    ['Lyrics support with karaoke mode', 'Soporte de letras con modo karaoke'],
    ['Recently Played tracking for easy history access', 'Seguimiento de reproducciones recientes para un fácil acceso al historial'],
    ['Comprehensive Personal Library for favorites', 'Biblioteca personal completa para favoritos'],
    ['Intelligent API caching for improved performance', 'Caché de API inteligente para mejorar el rendimiento'],
    ['Offline-capable Progressive Web App (PWA)', 'PWA con capacidad para trabajar sin conexión'],
    ['Media Session API integration for system controls', 'Integración de Media Session API para controles del sistema'],
    ['Queue management with shuffle and repeat modes', 'Gestión de la cola con modos aleatorio y repetición'],
    ['Track downloads with automatic metadata embedding', 'Descargas de pistas con incrustación automática de metadatos'],
    ['Multiple API instance support with failover', 'Soporte de múltiples instancias de API con recuperación de fallos'],
    ['Dark, minimalist interface optimized for focus', 'Interfaz oscura y minimalista optimizada para el enfoque'],
    ['Customizable themes', 'Temas personalizables'],
    ['Keyboard shortcuts for power users', 'Atajos de teclado para usuarios avanzados'],
    ['Technology Stack', 'Tecnologías Usadas'],
    ['Donate to Monochrome', 'Donar a Monochrome'],
    ['If Monochrome has been useful to you and you\'re able to, consider making a donation.', 'Si Monochrome te ha sido útil y puedes hacerlo, considera hacer una donación.'],
    ['It helps pay for the server and domain, and you get to support us :)', 'Ayuda a pagar el servidor y el dominio, y además nos apoyas :)'],
    ['View on GitHub', 'Ver en GitHub'],
    ['This is an independent client and is not affiliated with or endorsed by TIDAL or any', 'Este es un cliente independiente y no está afiliado ni respaldado por TIDAL ni por ningún otro'],
    ['music streaming service.', 'servicio de transmisión de música.'],
    [
        'This application does not host, store, or distribute any media files. <br />',
        'Esta aplicación no aloja, almacena ni distribuye archivos multimedia. <br />'
    ],
    [
        'All content displayed or accessed through this app is provided by third‑party services',
        'Todo el contenido mostrado o accedido a través de esta aplicación es proporcionado por servicios de terceros'
    ],
    [
        'and APIs that are publicly available on the internet. <br />',
        'y API que están disponibles públicamente en Internet. <br />'
    ],
    [
        'We do not control, operate, or maintain any external content sources and are not',
        'No controlamos, operamos ni mantenemos fuentes de contenido externas y no'
    ],
    [
        'responsible for the accuracy, availability, or legality of any content provided by third',
        'somos responsables de la precisión, disponibilidad o legalidad del contenido proporcionado por terceros.'
    ],
    [
        'parties. <br />',
        '<br />'
    ],
    [
        'Users are solely responsible for how they use this application and for ensuring that',
        'Los usuarios son los únicos responsables de cómo utilizan esta aplicación y de asegurarse de que'
    ],
    [
        'their use complies with applicable laws and regulations in their jurisdiction.',
        'su uso cumpla con las leyes y regulaciones aplicables en su jurisdicción.'
    ],

    ['Sign Up / Sign In', 'Registrarse / Iniciar Sesión'],
    ['Make an account to allow syncing your library between devices.', 'Crea una cuenta para poder sincronizar tu biblioteca entre dispositivos.'],
    ['Connect with Google', 'Conectar con Google'],
    ['Connect with Email', 'Conectar con Email'],
    ['View My Profile', 'Ver mi perfil'],
    ['Sync your library across devices', 'Sincroniza tu biblioteca en todos tus dispositivos'],
    ['Signed in as ', 'Ha iniciado sesión como '],
    ['We only store music data and a randomized ID to find out which Google/Email account is', 'Solo almacenamos datos de música y un ID aleatorio para identificar a qué cuenta de Google/Email'],
    ['which.', 'corresponde.'],
    ['All data is anonymous. We do not store anything like emails, usernames, or anything', 'Todos los datos son anónimos. No almacenamos correos electrónicos, nombres de usuario ni nada'],
    ['sensitive.', 'confidencial.'],
    ['However, if you want complete control over your data, we allow you to use your own Database', 'Sin embargo, si quieres el control total sobre tus datos, te permitimos usar tu propia configuración'],
    ['Configuration.', 'de Base de Datos.'],
    ['Advanced: Custom Configuration', 'Avanzado: Configuración Personalizada'],

    ['Monochrome Official App', 'Aplicación Oficial Monochrome'],
    ['Install the Monochrome Desktop App for a refined & improved music listening experience.', 'Instala la aplicación de escritorio Monochrome para una experiencia de escucha de música refinada y mejorada.'],
    ['Download Windows Version', 'Descargar Versión de Windows'],
    ['Download Linux Version', 'Descargar Versión de Linux'],
    ['The App is still in Beta. Please report any issues in our', 'La aplicación forma parte de una Beta. Por favor, informa de cualquier problema en nuestro'],
    ['Discord server.', 'servidor de Discord.'],

    ['Select a song', 'Selecciona una canción'],
    ['title="Mute"', 'title="Silenciar"'],
    ['title="Queue"', 'title="Cola"'],

    ['title="Shuffle"', 'title="Aleatorio"'],
    ['title="Previous"', 'title="Anterior"'],
    ['title="Play"', 'title="Reproducir"'],
    ['title="Next"', 'title="Siguiente"'],
    ['title="Repeat"', 'title="Repetir"'],
    ['title="Add to Playlist"', 'title="Añadir a Playlist"'],
    ['title="Track Mix"', 'title="Mix de pista"'],
    ['title="Lyrics"', 'title="Letras"'],
    ['title="Download current track"', 'title="Descargar pista actual"'],
    ['title="Cast"', 'title="Transmitir"']
];

replacements.forEach(([eng, esp]) => {
    html = html.split(eng).join(esp);
});

fs.writeFileSync(htmlFile, html, 'utf8');
console.log('2nd phase replacements completed.');
