import * as fs from 'fs';
import * as path from 'path';

const INDEX_PATH = 'c:/Users/FERAZ-30/OneDrive - ADMINISTRATEGIA/Documentos/Proyectos/monochrome/monochrome/index.html';

let content = fs.readFileSync(INDEX_PATH, 'utf-8');

const replacements = [
    [/<html lang="en">/g, '<html lang="es">'],
    [/Shuffle play/g, 'Reproducción aleatoria'],
    [/Start mix/g, 'Iniciar mix'],
    [/Play next/g, 'Reproducir a continuación'],
    [/Add to queue/g, 'Añadir a la cola'],
    [/>Like</g, '>Me gusta<'],
    [/Save album to library/g, 'Guardar álbum en la biblioteca'],
    [/Save playlist to library/g, 'Guardar playlist en la biblioteca'],
    [/>Pin</g, '>Fijar<'],
    [/Add to playlist/g, 'Añadir a playlist'],
    [/Go to artist/g, 'Ir al artista'],
    [/Go to album/g, 'Ir al álbum'],
    [/Copy link/g, 'Copiar enlace'],
    [/Open in new tab/g, 'Abrir en nueva pestaña'],
    [/Track info/g, 'Info. de la pista'],
    [/Open original URL/g, 'Abrir URL original'],
    [/>Download</g, '>Descargar<'],
    [/Block track/g, 'Bloquear pista'],
    [/Unblock track/g, 'Desbloquear pista'],
    [/Block album/g, 'Bloquear álbum'],
    [/Unblock album/g, 'Desbloquear álbum'],
    [/Block artist/g, 'Bloquear artista'],
    [/Unblock artist/g, 'Desbloquear artista'],
    [/Playlist Order/g, 'Orden de la playlist'],
    [/Date Added \(Newest\)/g, 'Fecha de adición (Más recientes)'],
    [/Date Added \(Oldest\)/g, 'Fecha de adición (Más antiguos)'],
    [/Title \(A-Z\)/g, 'Título (A-Z)'],
    [/Artist \(A-Z\)/g, 'Artista (A-Z)'],
    [/Album \(A-Z\)/g, 'Álbum (A-Z)'],
    [/Create Playlist/g, 'Crear Playlist'],
    [/Playlist name/g, 'Nombre de la playlist'],
    [/Cover image URL/g, 'URL de la imagen de portada'],
    [/>Upload</g, '>Subir<'],
    [/>or URL</g, '>o URL<'],
    [/Description \(optional\)/g, 'Descripción (opcional)'],
    [/Import from CSV/g, 'Importar desde CSV'],
    [/Import from JSPF/g, 'Importar desde JSPF'],
    [/Import from XSPF/g, 'Importar desde XSPF'],
    [/Import from XML/g, 'Importar desde XML'],
    [/Import from M3U\/M3U8/g, 'Importar desde M3U/M3U8'],
    [/Public Playlist/g, 'Playlist Pública'],
    [/Visible to anyone with the link./g, 'Visible para cualquiera con el enlace.'],
    [/>Share</g, '>Compartir<'],
    [/>Cancel</g, '>Cancelar<'],
    [/>Save</g, '>Guardar<'],
    [/Edit Profile/g, 'Editar Perfil'],
    [/>Username</g, '>Nombre de usuario<'],
    [/>Display Name</g, '>Nombre a mostrar<'],
    [/>Avatar URL</g, '>URL del Avatar<'],
    [/>Banner URL</g, '>URL del Banner<'],
    [/>Status \(Listening to...\)</g, '>Estado (Escuchando...)<'],
    [/>Favorite Albums \(Max 5\)</g, '>Álbumes Favoritos (Max 5)<'],
    [/>About Me</g, '>Sobre Mí<'],
    [/Tell us about yourself/g, 'Cuéntanos sobre ti'],
    [/>Website</g, '>Sitio web<'],
    [/>Last.fm Username</g, '>Usuario de Last.fm<'],
    [/>Privacy</g, '>Privacidad<'],
    [/>Public Playlists</g, '>Playlists Públicas<'],
    [/>Show Last.fm Link & Stats</g, '>Mostrar Enlace y Estadísticas de Last.fm<'],
    [/>Save Profile</g, '>Guardar Perfil<'],
    [/Search for a song or album.../g, 'Buscar una canción o álbum...'],
    [/Search for an album.../g, 'Buscar un álbum...'],
    [/Create Folder/g, 'Crear Carpeta'],
    [/Folder name/g, 'Nombre de la carpeta'],
    [/Icon URL \(optional\)/g, 'URL del icono (opcional)'],
    [/Email Authentication/g, 'Autenticación por Email'],
    [/Email Address/g, 'Correo Electrónico'],
    [/>Password</g, '>Contraseña<'],
    [/>Sign In</g, '>Iniciar Sesión<'],
    [/>Sign Up</g, '>Registrarse<'],
    [/Forgot Password\?/g, '¿Olvidaste tu contraseña?'],
    [/Keyboard Shortcuts/g, 'Atajos de teclado'],
    [/Play \/ Pause/g, 'Reproducir / Pausar'],
    [/Seek forward 10s/g, 'Avanzar 10s'],
    [/Seek backward 10s/g, 'Retroceder 10s'],
    [/Next track/g, 'Siguiente pista'],
    [/Previous track/g, 'Pista anterior'],
    [/Volume up/g, 'Subir volumen'],
    [/Volume down/g, 'Bajar volumen'],
    [/Mute \/ Unmute/g, 'Silenciar / Activar sonido'],
    [/Toggle shuffle/g, 'Alternar reproducción aleatoria'],
    [/Toggle repeat/g, 'Alternar repetición'],
    [/Open queue/g, 'Abrir cola'],
    [/Toggle lyrics/g, 'Alternar letras'],
    [/Focus search/g, 'Enfocar búsqueda'],
    [/Close modals/g, 'Cerrar ventanas'],
    [/>Note</g, '>Nota<'],
    [/Missing Tracks:/g, 'Pistas faltantes:'],
    [/>OK</g, '>Aceptar<'],
    [/Sleep Timer/g, 'Temporizador de apagado'],
    [/>5 minutes</g, '>5 minutos<'],
    [/>15 minutes</g, '>15 minutos<'],
    [/>30 minutes</g, '>30 minutos<'],
    [/>1 hour</g, '>1 hora<'],
    [/>2 hours</g, '>2 horas<'],
    [/>Custom</g, '>Personalizado<'],
    [/>Set</g, '>Establecer<'],
    [/Download Discography/g, 'Descargar Discografía'],
    [/Select which releases to download for/g, 'Selecciona qué lanzamientos descargar para'],
    [/Albums/g, 'Álbumes'],
    [/EPs/g, 'EPs'],
    [/Singles/g, 'Sencillos'],
    [/Custom Database\/Auth/g, 'Base de Datos/Autenticación Personalizada'],
    [/Reset to Defaults/g, 'Restablecer a valores predeterminados'],
    [/Save & Reload/g, 'Guardar y Recargar'],
    [/Theme Store/g, 'Tienda de Temas'],
    [/>Browse</g, '>Explorar<'],
    [/>Back</g, '>Volver<'],
    [/Apply Theme/g, 'Aplicar Tema'],
    [/Created:/g, 'Creado:'],
    [/Updated:/g, 'Actualizado:'],
    [/Installs:/g, 'Instalaciones:'],
    [/>Description</g, '>Descripción<'],
    [/Search themes.../g, 'Buscar temas...'],
    [/You need to be logged in to upload themes./g, 'Necesitas iniciar sesión para subir temas.'],
    [/Go to Login/g, 'Ir a Iniciar Sesión'],
    [/>Theme Name</g, '>Nombre del Tema<'],
    [/Author Website \(Optional\)/g, 'Sitio Web del Autor (Opcional)'],
    [/>Home</g, '>Inicio<'],
    [/>Search</g, '>Buscar<'],
    [/>Library</g, '>Biblioteca<'],
    [/>Settings</g, '>Ajustes<'],
    [/>Profile</g, '>Perfil<'],
    [/>Queue</g, '>Cola<'],
    [/>Lyrics</g, '>Letras<'],
    [/>Playlists</g, '>Playlists<'],
    [/>Downloads</g, '>Descargas<'],
    [/>History</g, '>Historial<'],
    [/>Log In</g, '>Iniciar Sesión<'],
    [/>Sign Out</g, '>Cerrar Sesión<']
];

let newContent = content;

for (const [regex, replacement] of replacements) {
    newContent = newContent.replace(regex, replacement);
}

fs.writeFileSync(INDEX_PATH, newContent, 'utf-8');

console.log('Script completed. ' + (content !== newContent ? 'Changes were made.' : 'No changes were made.'));
